# Generated by Django 5.1.6 on 2026-01-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(help_text='Enter salary in LPA (example: 2.3)'),
        ),
    ]
